<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="TM_Article"
           tests="10"
           failures="1"
           errors="0"
           skipped="0"
           time="140.171">
  <properties />
            <testcase name="TC_JOOMLA_ARTICLE_008" time="17.526" classname="testcases.article.TM_Article_001">
                <failure type="java.lang.AssertionError"
                  message="Test Failed"
              >
<![CDATA[java.lang.AssertionError: Test Failed
  org.testng.Assert.fail(Assert.java:83)
  abstracts.AbstractTest.verifyTrue(AbstractTest.java:36)
  testcases.article.TM_Article_001.TC_JOOMLA_ARTICLE_008(TM_Article_001.java:49)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="TC_JOOMLA_ARTICLE_003" time="6.639" classname="testcases.article.TM_Article_001" />
                <testcase name="TC_JOOMLA_ARTICLE_016" time="40.565" classname="testcases.article.TM_Article_001" />
                <testcase name="TC_JOOMLA_ARTICLE_017" time="2.852" classname="testcases.article.TM_Article_001" />
                <testcase name="TC_JOOMLA_ARTICLE_002" time="15.759" classname="testcases.article.TM_Article_001" />
                <testcase name="TC_JOOMLA_ARTICLE_004" time="6.640" classname="testcases.article.TM_Article_001" />
                <testcase name="TC_JOOMLA_ARTICLE_010" time="8.243" classname="testcases.article.TM_Article_001" />
                <testcase name="TC_JOOMLA_ARTICLE_001" time="21.521" classname="testcases.article.TM_Article_001" />
                <testcase name="TC_JOOMLA_ARTICLE_009" time="2.960" classname="testcases.article.TM_Article_001" />
                <testcase name="TC_JOOMLA_ARTICLE_005" time="17.466" classname="testcases.article.TM_Article_001" />
      
</testsuite>
